# Generated by Django 5.0.3 on 2024-03-31 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_name',
        ),
        migrations.AddField(
            model_name='chat',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 13, 10, 53, 120495)),
        ),
    ]
