# Generated by Django 5.0.3 on 2024-03-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_chat_chat_name_chat_last_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='member0',
            new_name='members',
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
