# Generated by Django 5.0.3 on 2024-03-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_rename_member0_chat_members_alter_chat_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_key',
            field=models.BinaryField(),
        ),
    ]
