# Generated by Django 5.0.3 on 2024-04-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chat_chat_key_alter_chat_last_used_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_key',
            field=models.CharField(max_length=32),
        ),
    ]
