# Generated by Django 5.0.3 on 2024-04-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_chat_chat_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_key',
            field=models.BinaryField(),
        ),
    ]
